services:
  db:
    image: mongo:latest
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=vapestation
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 27017
    ports:
      - "27017:27017"
    networks:
      - vapestation

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  db-data:
  letsencrypt:

secrets:
  db-password:
    file: ./db/password.txt

networks:
  vapestation:
    name: vapestation
    driver: bridge
