import "@vapestation/ui/styles.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Inter } from "next/font/google";
import { Toaster } from "@vapestation/ui/sonner";
import TopLoaderBar from "@vapestation/ui/top-loading-bar";

export const metadata = {
  title: "Vapestation Admin",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${inter.className}`}>
      <body>
        <TopLoaderBar />
        <ClerkProvider
          appearance={{
            layout: {
              shimmer: true,
            },
            variables: {
              colorPrimary: "#2E67FF",
            },
          }}
        >
          {children}
          <Toaster
            toastOptions={{
              duration: 2000,
            }}
          />
        </ClerkProvider>
      </body>
    </html>
  );
}
